# Generated by Django 5.2.5 on 2026-08-08 18:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('kind', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='business', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('category', models.CharField(max_length=80)),
                ('company_name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('trust_score', models.DecimalField(decimal_places=1, default=40.0, editable=False, max_digits=4)),
                ('trust_level', models.CharField(choices=[('unverified', 'Unverified'), ('developing', 'Developing'), ('trusted', 'Trusted'), ('high_trust', 'High trust')], default='unverified', editable=False, max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('identity_key_fingerprint', models.CharField(blank=True, editable=False, max_length=64)),
                ('identity_verified_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('online', models.BooleanField(default=True)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('blocked_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verified', '-trust_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('identity_verified', 'Identity verified'), ('task_completed', 'Task completed'), ('peer_attestation', 'Peer attestation'), ('dispute_resolved', 'Dispute resolved'), ('policy_violation', 'Policy violation')], max_length=30)),
                ('outcome', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('score_delta', models.DecimalField(decimal_places=1, max_digits=4)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_trust_events', to='agents.agent')),
                ('subject_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_events', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'personal')), fields=('owner',), name='one_personal_agent_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='trustevent',
            constraint=models.CheckConstraint(condition=models.Q(('score_delta__gte', -20), ('score_delta__lte', 10)), name='trust_event_delta_range'),
        ),
    ]
