# Generated by Django 5.2.5 on 2026-08-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hosting_type',
            field=models.CharField(choices=[('managed', 'Managed by Agen'), ('external', 'External endpoint')], default='managed', max_length=20),
        ),
    ]
