# Generated by Django 5.2.5 on 2026-08-11 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_network_handle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending_approval', max_length=24)),
                ('auto_approved', models.BooleanField(default=False)),
                ('requested_scopes', models.JSONField(default=list)),
                ('trust_score_snapshot', models.DecimalField(decimal_places=1, max_digits=4)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_connections', to='agents.agent')),
                ('requester_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_connections', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_grant', to='agents.agentconnection')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('request_text', models.TextField()),
                ('discovery_spec', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('discovering', 'Discovering'), ('awaiting_approval', 'Awaiting approval'), ('connecting', 'Connecting'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='discovering', max_length=24)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
                ('personal_agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_tasks', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentconnection',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='agents.task'),
        ),
        migrations.CreateModel(
            name='TaskCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField()),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trust_score_snapshot', models.DecimalField(decimal_places=1, max_digits=4)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_candidates', to='agents.agent')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='agents.task')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('summary', models.TextField()),
                ('structured_result', models.JSONField(default=dict)),
                ('evidence_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='agents.agentconnection')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='agents.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agents.task')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddConstraint(
            model_name='agentconnection',
            constraint=models.UniqueConstraint(fields=('task', 'provider_agent'), name='unique_provider_connection_per_task'),
        ),
        migrations.AddConstraint(
            model_name='agentconnection',
            constraint=models.CheckConstraint(condition=models.Q(('requester_agent', models.F('provider_agent')), _negated=True), name='connection_agents_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='taskcandidate',
            constraint=models.UniqueConstraint(fields=('task', 'agent'), name='unique_agent_candidate_per_task'),
        ),
        migrations.AddConstraint(
            model_name='taskcandidate',
            constraint=models.UniqueConstraint(fields=('task', 'rank'), name='unique_candidate_rank_per_task'),
        ),
        migrations.AddConstraint(
            model_name='taskstep',
            constraint=models.UniqueConstraint(fields=('task', 'position'), name='unique_task_step_position'),
        ),
    ]
