# Generated by Django 5.2.5 on 2026-08-11 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_conversation_conversationmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=80)),
                ('detail', models.CharField(blank=True, max_length=240)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentKnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(choices=[('note', 'Business note'), ('faq', 'FAQ'), ('document', 'Document'), ('website', 'Website')], default='note', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('content_ciphertext', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_sources', to='agents.agent')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('needs_configuration', 'Needs configuration')], max_length=24)),
                ('matched_sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(blank=True, max_length=60)),
                ('verification_status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=16)),
                ('business_domain', models.CharField(blank=True, max_length=160)),
                ('instructions', models.TextField(blank=True)),
                ('tone', models.CharField(default='Helpful and concise', max_length=80)),
                ('human_handoff', models.TextField(blank=True)),
                ('verification_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managed_profile', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('availability', models.CharField(default='Available', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_items', to='agents.agent')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('agent', 'sku'), name='unique_catalog_sku_per_agent')],
            },
        ),
        migrations.CreateModel(
            name='AgentToolConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('connected', 'Connected'), ('error', 'Error'), ('disconnected', 'Disconnected')], default='configured', max_length=16)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('config_ciphertext', models.TextField(blank=True)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_connections', to='agents.agent')),
            ],
            options={
                'ordering': ['display_name'],
                'constraints': [models.UniqueConstraint(fields=('agent', 'provider'), name='unique_tool_provider_per_agent')],
            },
        ),
    ]
