# Generated by Django 5.2.5 on 2026-08-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_agentauditevent_agentknowledgesource_agenttestrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedagentprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='country',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='evidence_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='registration_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='requested_verification_level',
            field=models.CharField(choices=[('none', 'Not verified'), ('basic', 'Basic verified'), ('business', 'Business verified'), ('enhanced', 'Enhanced verified')], default='business', max_length=16),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='supporting_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='verification_level',
            field=models.CharField(choices=[('none', 'Not verified'), ('basic', 'Basic verified'), ('business', 'Business verified'), ('enhanced', 'Enhanced verified')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='managedagentprofile',
            name='verification_method',
            field=models.CharField(choices=[('none', 'Not submitted'), ('domain_email', 'Domain email'), ('manual_review', 'Manual business review'), ('development', 'Local development')], default='none', max_length=24),
        ),
    ]
