# Generated by Django 5.2.5 on 2026-08-11 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_managedagentprofile_business_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcatalogitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentknowledgesource',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GuestAgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('prompt_ciphertext', models.TextField()),
                ('response_ciphertext', models.TextField()),
                ('matched_sources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_messages', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicAgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('unlisted', 'Unlisted'), ('public', 'Public')], default='private', max_length=16)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('public_description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('published_capabilities', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('public_location', models.CharField(blank=True, max_length=120)),
                ('public_chat_enabled', models.BooleanField(default=False)),
                ('guest_daily_limit', models.PositiveSmallIntegerField(default=20)),
                ('show_catalog', models.BooleanField(default=True)),
                ('show_trust_history', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='agents.agent')),
            ],
        ),
    ]
