from django.urls import path

from .views import (
    AgentDetailView,
    AgentListView,
    BusinessAgentView,
    DashboardView,
    PersonalAgentProvisionView,
    PublicAgentHandleView,
    PublicAgentVerificationView,
    PublicTrustHistoryView,
)
from .resolver_views import (
    ConnectionApprovalView,
    ConnectionRequestView,
    ConnectionResultView,
    ResolverDiscoveryView,
    ProviderConnectionListView,
    TaskDetailView,
    TaskListView,
)
from .conversation_views import ConversationDetailView, ConversationListCreateView, ConversationMessageView
from .managed_views import (
    ManagedAgentActivationView,
    ManagedAgentCatalogDeleteView,
    ManagedAgentCatalogView,
    ManagedAgentKnowledgeDeleteView,
    ManagedAgentKnowledgeView,
    ManagedAgentSandboxView,
    ManagedAgentSetupView,
    ManagedAgentTemplateView,
    ManagedAgentToolDeleteView,
    ManagedAgentToolView,
    ManagedAgentVerificationView,
)
from .public_agent_views import (
    OwnerPublicProfileView,
    PublicAgentGuestChatView,
    PublicAgentManifestView,
    PublicAgentProfileView,
    PublicAgentQrView,
)

urlpatterns = [
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("conversations/", ConversationListCreateView.as_view(), name="conversation-list-create"),
    path("conversations/<uuid:conversation_id>/", ConversationDetailView.as_view(), name="conversation-detail"),
    path("conversations/<uuid:conversation_id>/messages/", ConversationMessageView.as_view(), name="conversation-message"),
    path("resolver/discover/", ResolverDiscoveryView.as_view(), name="resolver-discover"),
    path("resolver/tasks/", TaskListView.as_view(), name="resolver-task-list"),
    path("resolver/tasks/<uuid:task_id>/", TaskDetailView.as_view(), name="resolver-task-detail"),
    path("resolver/tasks/<uuid:task_id>/connect/", ConnectionRequestView.as_view(), name="resolver-connect"),
    path("resolver/connections/<uuid:connection_id>/approve/", ConnectionApprovalView.as_view(), name="resolver-approve"),
    path("resolver/connections/<uuid:connection_id>/result/", ConnectionResultView.as_view(), name="resolver-result"),
    path("resolver/provider/connections/", ProviderConnectionListView.as_view(), name="resolver-provider-connections"),
    path("agents/", AgentListView.as_view(), name="agent-list"),
    path("agents/personal/provision/", PersonalAgentProvisionView.as_view(), name="personal-agent-provision"),
    path("agents/business/", BusinessAgentView.as_view(), name="business-agent-list-create"),
    path("agents/business/<uuid:agent_id>/setup/", ManagedAgentSetupView.as_view(), name="managed-agent-setup"),
    path("agents/business/<uuid:agent_id>/template/<slug:template_key>/", ManagedAgentTemplateView.as_view(), name="managed-agent-template"),
    path("agents/business/<uuid:agent_id>/verification/", ManagedAgentVerificationView.as_view(), name="managed-agent-verification"),
    path("agents/business/<uuid:agent_id>/knowledge/", ManagedAgentKnowledgeView.as_view(), name="managed-agent-knowledge"),
    path("agents/business/<uuid:agent_id>/knowledge/<uuid:source_id>/", ManagedAgentKnowledgeDeleteView.as_view(), name="managed-agent-knowledge-delete"),
    path("agents/business/<uuid:agent_id>/catalog/", ManagedAgentCatalogView.as_view(), name="managed-agent-catalog"),
    path("agents/business/<uuid:agent_id>/catalog/<uuid:item_id>/", ManagedAgentCatalogDeleteView.as_view(), name="managed-agent-catalog-delete"),
    path("agents/business/<uuid:agent_id>/tools/", ManagedAgentToolView.as_view(), name="managed-agent-tool"),
    path("agents/business/<uuid:agent_id>/tools/<uuid:connection_id>/", ManagedAgentToolDeleteView.as_view(), name="managed-agent-tool-delete"),
    path("agents/business/<uuid:agent_id>/sandbox/", ManagedAgentSandboxView.as_view(), name="managed-agent-sandbox"),
    path("agents/business/<uuid:agent_id>/activate/", ManagedAgentActivationView.as_view(), name="managed-agent-activate"),
    path("agents/business/<uuid:agent_id>/public-profile/", OwnerPublicProfileView.as_view(), name="owner-public-profile"),
    path("public/agents/<slug:network_handle>/", PublicAgentProfileView.as_view(), name="public-agent-profile"),
    path("public/agents/<slug:network_handle>/manifest/", PublicAgentManifestView.as_view(), name="public-agent-manifest"),
    path("public/agents/<slug:network_handle>/qr/", PublicAgentQrView.as_view(), name="public-agent-qr"),
    path("public/agents/<slug:network_handle>/chat/", PublicAgentGuestChatView.as_view(), name="public-agent-guest-chat"),
    path("agents/handle/<slug:network_handle>/", PublicAgentHandleView.as_view(), name="agent-handle"),
    path("agents/verify/<uuid:agent_id>/", PublicAgentVerificationView.as_view(), name="agent-verification"),
    path("agents/verify/<uuid:agent_id>/trust/", PublicTrustHistoryView.as_view(), name="agent-trust-history"),
    path("agents/<slug:slug>/", AgentDetailView.as_view(), name="agent-detail"),
]
