import type { Agent, DashboardSnapshot } from "@/lib/types";

export const mockPersonalAgent: Agent = {
  id: 1,
  name: "Abednego Agent",
  slug: "abednego-agent",
  kind: "personal",
  status: "active",
  category: "Personal",
  companyName: "Private Agent",
  location: "Lagos, Nigeria",
  endpoint: "local://agent.abednego",
  summary: "An autonomous personal agent that learns preferences, manages requests, and coordinates trusted business agents.",
  trustScore: 98.4,
  verified: true,
  online: true,
  capabilities: ["Search", "Compare", "Negotiate", "Book"],
  allowedActions: ["Plan trips", "Compare offers", "Draft requests", "Approve purchases"],
  blockedActions: ["Send payments without approval", "Share private data automatically"],
};

export const mockAgents: Agent[] = [
  {
    id: 2,
    name: "Eko Hotel Booking Agent",
    slug: "eko-hotel-booking-agent",
    kind: "business",
    status: "active",
    category: "Hospitality",
    companyName: "Eko Hotel",
    location: "Lagos, Nigeria",
    endpoint: "agent.ekohotels.com",
    summary: "AI agent representing Eko Hotel for room discovery, reservations, pricing, and customer support.",
    trustScore: 98.4,
    verified: true,
    online: true,
    capabilities: ["Room availability", "Booking", "Pricing", "Negotiation", "Customer support"],
    allowedActions: ["Quote rooms", "Reserve rooms", "Offer approved discounts"],
    blockedActions: ["Modify company policy", "Access unrelated customer data", "Issue unrestricted refunds"],
  },
  {
    id: 3,
    name: "Paystack Payment Agent",
    slug: "paystack-payment-agent",
    kind: "business",
    status: "active",
    category: "Payments",
    companyName: "Paystack",
    location: "Nigeria",
    endpoint: "agent.paystack.com",
    summary: "Handles payment requests, verification, and transaction status updates for supported businesses.",
    trustScore: 99.1,
    verified: true,
    online: true,
    capabilities: ["Payment requests", "Payment verification", "Transaction status"],
    allowedActions: ["Create payment intents", "Validate payments", "Confirm transaction state"],
    blockedActions: ["Access raw card data", "Alter settlement rules"],
  },
  {
    id: 4,
    name: "Dell Pro Support Agent",
    slug: "dell-pro-support-agent",
    kind: "business",
    status: "active",
    category: "Hardware",
    companyName: "Dell",
    location: "Remote",
    endpoint: "support.dell.com/agent",
    summary: "Supports product guidance, compatibility questions, and approved sales support flows.",
    trustScore: 96.7,
    verified: true,
    online: false,
    capabilities: ["Product guidance", "Compatibility", "Support routing"],
    allowedActions: ["Provide configuration guidance", "Open support tickets"],
    blockedActions: ["Override warranties", "Access customer payment methods"],
  },
];

export const mockDashboard: DashboardSnapshot = {
  greeting: "Good afternoon, Abednego",
  metrics: {
    my_agents: 4,
    connected_agents: 128,
    network_requests: 2841,
    successful_transactions: 1204,
  },
  personal_agent: mockPersonalAgent,
  featured_agents: mockAgents.slice(0, 3),
  recent_activity: [
    {
      title: "Trip planning request resolved",
      detail: "Personal agent matched the best hotel and flight combination within budget.",
      created_at: "2026-08-08T08:15:00.000Z",
      agent__name: "Abednego Agent",
      agent__slug: "abednego-agent",
    },
    {
      title: "New business agent verified",
      detail: "Eko Hotel Booking Agent completed verification and trust scoring.",
      created_at: "2026-08-08T07:40:00.000Z",
      agent__name: "Eko Hotel Booking Agent",
      agent__slug: "eko-hotel-booking-agent",
    },
  ],
};

